SQL_841: Add string functions formulas
mongodb/mongo-tableau-connector pull request #12
Opened 2022-05-10 18:15 UTC by nbagnard

2022-05-11 21:42 UTC, bucaojit requested changes
Nice work finding how to implement the formulas using the existing functions!

I had one comment on the `RIGHT` function

2022-05-11 21:42 UTC, bucaojit commented on connector/dialect.tdd
> +     <formula>(CASE WHEN %2 &lt;= 0 THEN (CASE WHEN %1 IS NULL THEN NULL ELSE '' END) WHEN %2 &gt;= CHAR_LENGTH(%1) THEN %1 ELSE SUBSTRING(%1 FROM (CHAR_LENGTH(%1) - %2 - 1) FOR %2) END)</formula>
```suggestion
     <formula>(CASE WHEN %2 &lt;= 0 THEN (CASE WHEN %1 IS NULL THEN NULL ELSE '' END) WHEN %2 &gt;= CHAR_LENGTH(%1) THEN %1 ELSE SUBSTRING(%1 FROM (CHAR_LENGTH(%1) - %2) FOR %2) END)</formula>
```
There may be an off by one error with the 'RIGHT' formula.  
For example if I try `SELECT SUBSTRING('calculation' FROM (CHAR_LENGTH('calculation') - 4 - 1) FOR 4)`
I get `atio` and not the expected `tion`.

2022-05-12 13:35 UTC, nbagnard commented on connector/dialect.tdd
> +     <formula>(CASE WHEN %2 &lt;= 0 THEN (CASE WHEN %1 IS NULL THEN NULL ELSE '' END) WHEN %2 &gt;= CHAR_LENGTH(%1) THEN %1 ELSE SUBSTRING(%1 FROM (CHAR_LENGTH(%1) - %2 - 1) FOR %2) END)</formula>
You are totally right!
Fixed it now :)

2022-05-12 17:46 UTC, bucaojit approved these changes
Thanks for fixing the RIGHT formula. 
Looks good.

2022-05-16 17:52 UTC, varsha804 approved these changes
lgtm!

2022-05-17 10:14 UTC, nbagnard commented
evergreen merge

2022-05-17 10:16 UTC, merged