SQL-842: Implement required Tableau date functions in connector dialect definition
mongodb/mongo-tableau-connector pull request #22
Opened 2022-07-08 21:44 UTC by varsha804

2022-07-13 21:44 UTC, nbagnard approved these changes
Just a side comment, but you were able to test them out and make sure that things worked the way we expect them to, isn't it?

2022-07-14 01:06 UTC, bucaojit requested changes
Nice work getting the date functions completed! 

Just a few suggestions.

2022-07-14 01:06 UTC, bucaojit commented on connector/dialect.tdd
> +    <function group='date' name='DATEADD' return-type='datetime'>
Let's switch the `function` to `date-function` and remove the `group='date'` for all these functions as is [done here](https://github.com/tableau/connector-plugin-sdk/blob/8d53af1b834aa1b3e5c38d57042b03aac5adc58a/samples/components/dialects/FullFunctionMap.tdd#L1535).  
Such as: `<date-function name='DATEADD' return-type='datetime'>`

2022-07-14 01:06 UTC, bucaojit commented on connector/dialect.tdd
> +    </function>
We can move these added functions to the end of the '\<function-map\>' section as they will not have a `group`.

2022-07-14 17:18 UTC, varsha804 commented on connector/dialect.tdd
> +    <function group='date' name='DATEADD' return-type='datetime'>
Done!

2022-07-14 17:18 UTC, varsha804 commented on connector/dialect.tdd
> +    </function>
Done

2022-07-14 17:35 UTC, bucaojit approved these changes
LGTM! 💯

2022-07-14 18:22 UTC, varsha804 commented
evergreen merge

2022-07-14 18:25 UTC, merged